# This code has TWO parts:
# Part-1: Creation of EC2 Instance - UBUNTU Server
# Part-2: Creation of Security Group
# Part-3: Referring SecurityGroup to Instance

# Note: This will delete the existing EC2 instance and create a new one with Security Group attached

# ****************************************** Start PART-1 ******************************************
---
Resources:
  UbuntuServer:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-43a15f3e #Ubuntu Server
      InstanceType: t2.micro
      KeyName: ELBKeyPair

# ****************************************** END of Start PART-1 ************************************
# ****************************************** Start Start PART-3 ************************************
      SecurityGroupIds:
        - !Ref MySecurityGroup1
# ****************************************** END of PART-3 ************************************

# ****************************************** Start Start PART-2 ************************************
# 1. Create New Security Group
  MySecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: MySecurityGroup1
      GroupDescription: This is my first Security Group
      SecurityGroupIngress:
        CidrIp: 0.0.0.0/0
        Description: String
        FromPort: 22
        IpProtocol: tcp
        ToPort: 22
      Tags:
        -
          Key: KN1
          Value: MYSG1
      VpcId: vpc-ab9cadd3

# ****************************************** END of PART-2 ************************************
