---
Resources:
#****************************************** Start Instance-1 ******************************************
  SystemPicture1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f01d272 #Microsoft Windows Server 2012 Base
      KeyName: ELBKeyPair
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ELBRdpSG
        - !Ref ELBServerSG
#****************************************** End Instance-1 ******************************************

#****************************************** Start Instance-2 ******************************************
  SystemPicture2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1a
      ImageId: ami-0f01d272 #Microsoft Windows Server 2012 Base
      KeyName: ELBKeyPair
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ELBRdpSG
        - !Ref ELBServerSG
#****************************************** End Instance-2 ******************************************

#****************************************** Start Instance-3 ******************************************
  SystemVideo1:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-0f01d272 #Microsoft Windows Server 2012 Base
      KeyName: ELBKeyPair
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ELBRdpSG
        - !Ref ELBServerSG
#****************************************** End Instance-3 ******************************************

#****************************************** Start Instance-4 ******************************************
  SystemVideo2:
    Type: AWS::EC2::Instance
    Properties:
      AvailabilityZone: us-east-1b
      ImageId: ami-0f01d272 #Microsoft Windows Server 2012 Base
      KeyName: ELBKeyPair
      InstanceType: t2.micro
      SecurityGroups:
        - !Ref ELBRdpSG
        - !Ref ELBServerSG
#****************************************** End Instance-4 ******************************************


  # an elastic IP for our instance
  #  MyEIP:
  #    Type: AWS::EC2::EIP
  #    Properties:
  #      InstanceId: !Ref SysPicture-1
#      InstanceId: !Ref MicrosoftWindowsServer2012R2Base


  # our EC2 security group
  ELBRdpSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable RDP access via port 3389
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        FromPort: 3389
        IpProtocol: tcp
        ToPort: 3389

  # our second EC2 security group
  ELBServerSG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: allow connections from specified CIDR ranges
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 80
        ToPort: 80
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22



#        - IpProtocol: rdp
#          FromPort: 3389
#          ToPort: 3389
        #CidrIp: 192.168.1.1/32
